#!/bin/sh

handle_error() {
    echo "Failed to boot!"
    echo "Launching emergency shell..."
    setsid cttyhack /bin/sh
    halt
    while true; do sleep 1; done
}

trap handle_error EXIT

echo Welcome to ElliNet13 script Linux initramfs!

echo "[*] Mounting virtual filesystems..."
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "[*] Mounting root filesystem..."
