#!/bin/sh

handle_error() {
    echo "Failed to boot!"
    echo "Launching emergency shell..."
    setsid cttyhack /bin/sh
    halt
    while true; do sleep 1; done
}

trap handle_error EXIT

echo Welcome to ElliNet13 script Linux initramfs!

echo "[*] Mounting virtual filesystems..."
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "[*] Mounting root filesystem..."
CMDLINE="$(cat /proc/cmdline)"
echo "cmdline: $CMDLINE"

ROOTDEV=""
for arg in $CMDLINE; do
  case "$arg" in
    root=*)
      ROOTDEV="${arg#root=}"
      ;;
  esac
done

echo "root device: $ROOTDEV"
mkdir -p /newroot
mount -t ext4 "$ROOTDEV" /newroot
if [ $? -ne 0 ]; then
    echo "Error Code: $?" 
    echo "Failed to mount root device: $ROOTDEV"
    exit
fi

echo "[*] Switching to new root..."
mkdir -p /newroot/proc /newroot/sys /newroot/dev
mount --move /proc /newroot/proc
mount --move /sys  /newroot/sys
mount --move /dev  /newroot/dev
exec switch_root /newroot /sbin/init